import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Load the data generated by fetch_data.py
df = pd.read_csv('pvp_match_history.csv')

# Define features (X) and target outcome (y)
X = df[['brawler_power_level', 'team_synergy_score', 'map_win_rate_pct']]
y = df['match_outcome']

# Train a Random Forest model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)
print(f"Model successfully trained! Win-rate prediction accuracy: {accuracy * 100:.1f}%")
